// Re-exports from generated types (auto-generated by tygo from Go structs).
// Aliases maintain backwards compatibility with existing frontend code.

import type { ProgressSnapshot } from "./generated";

export type { Config, Export } from "./generated";
export type { DistTargetConf as DistTarget } from "./generated";
export type { SyncedFile, SyncRun, DownloadedRevision, DistJob } from "./generated";
export type { ActiveDownload, DiffEntry } from "./generated";

// Alias: generated ProgressSnapshot → frontend SyncProgress
export type SyncProgress = ProgressSnapshot;
export type { BrowseResponse as BrowseResult } from "./generated";
export type { DriveBrowseResponse as DriveBrowseResult } from "./generated";
export type {
  StatusResponse,
  SyncStartResponse,
  SyncStatusResponse,
  AuthTestResponse,
  AuthUser,
  BrowseResponse,
  BrowseItem,
  MakeDirResponse,
  DriveBrowseResponse,
  DriveBrowseItem,
  DeleteFilesResponse,
  DistributeResult,
  RevisionDownloadResponse,
  DistributeRequest,
} from "./generated";

// --- Verify ---

export interface VerifyResult {
  file_id: string;
  name: string;
  status: "ok" | "mismatch" | "missing" | "skipped";
  expected?: string;
  actual?: string;
}

export interface VerifyResponse {
  total: number;
  ok: number;
  mismatch: number;
  missing: number;
  skipped: number;
  results: VerifyResult[];
}

// --- Frontend-only types (no Go counterpart) ---

// Google Drive revision -- sourced from Google API response
export interface DriveRevision {
  id: string;
  modifiedTime: string;
  size: string;
  lastModifyingUser?: { displayName: string };
  mimeType: string;
  keepForever: boolean;
  originalFilename: string;
}

// Sync completion event from WebSocket
export interface SyncComplete {
  status: string;
  files_synced: number;
  files_failed: number;
  bytes_downloaded: number;
  duration_ms: number;
}

// WebSocket message union type
export type WSMessage =
  | { type: "sync_progress"; data: SyncProgress }
  | { type: "sync_complete"; data: SyncComplete }
  | { type: "pong" };
